Es el ejercicio 8.5

In [29]:
import numpy as np
from math import sqrt

In [49]:
def caida(h0=10,v0=0,g=-9.8,puntos=10):
    ttot=(v0+sqrt(v0**2-2*g*h0))/g
    t=np.linspace(0,ttot,puntos)
    h=h0+v0*t+0.5*g*t*t
    v=v0+g*t
    
    return h,v

In [45]:
(-10+sqrt(-10**2-2*(-9.81)*10))/9.81

-0.019555568991704023

In [39]:
tiempos=np.linspace(0,1.5,21)

In [40]:
tiempos


array([0.   , 0.075, 0.15 , 0.225, 0.3  , 0.375, 0.45 , 0.525, 0.6  ,
       0.675, 0.75 , 0.825, 0.9  , 0.975, 1.05 , 1.125, 1.2  , 1.275,
       1.35 , 1.425, 1.5  ])

In [50]:
caida()

(array([1.00000000e+01, 9.87654321e+00, 9.50617284e+00, 8.88888889e+00,
        8.02469136e+00, 6.91358025e+00, 5.55555556e+00, 3.95061728e+00,
        2.09876543e+00, 1.77635684e-15]),
 array([ 0.        ,  1.55555556,  3.11111111,  4.66666667,  6.22222222,
         7.77777778,  9.33333333, 10.88888889, 12.44444444, 14.        ]))